### ISSUE TITLE
Module not found: Error: Can't resolve 'gsap' in 'D:\OnGoing Projects\xnation-reactjs\node_modules\custom-cursor-react\dist'

### ISSUE THREAD

**Issue by ayoubkhan558** [ajmnz/custom-cursor-react#23] opened 2022-11-25 09:51 UTC
Compiled with problems:X

ERROR in ./node_modules/custom-cursor-react/dist/index.modern.js 3:0-28

Module not found: Error: Can't resolve 'gsap' in 'D:\OnGoing Projects\xnation-reactjs\node_modules\custom-cursor-react\dist'

![image](https://user-images.githubusercontent.com/99708427/203953298-73de6bf5-07fc-494e-840b-8f2ab0889e21.png)

**Comment by ajmnz** [comment] 2022-11-25 09:53
Duplicate of #20

**Closed as completed by ajmnz** 2022-11-25 09:53 UTC
